# Install PhpWiki
# https://sourceforge.net/projects/phpwiki/
#
# Requires the `puppet/archive` module
class phpwiki (
  $version         = '1.5.5',
  $source_url      = undef,
  $install_root    = undef,
  $owner           = 'root',
  $writeable_owner = 'apache',
  $group           = 'apache',

  # BEGIN config.ini
  $include_path                           = undef,
  $debug                                  = undef,
  $enable_edit_toolbar                    = undef,
  $js_searchreplace                       = undef,
  $enable_doubleclickedit                 = undef,
  $enable_wysiwyg                         = undef,
  $wysiwyg_backend                        = undef,
  $wysiwyg_default_pagetype_html          = undef,
  $upload_userdir                         = undef,
  $disable_units                          = undef,
  $units_exe                              = undef,
  $enable_xhtml_xml                       = undef,
  $enable_open_graph                      = undef,
  $enable_spamassassin                    = undef,
  $enable_spamblocklist                   = undef,
  $num_spam_links                         = undef,
  $disable_upload_only_allowed_extensions = undef,
  $google_links_nofollow                  = undef,
  $enable_ajax                            = undef,
  $enable_discussion_link                 = undef,
  $enable_captcha                         = undef,
  $use_captcha_random_word                = undef,
  $use_safe_dbsession                     = undef,
  $blog_default_empty_prefix              = undef,
  $enable_searchhighlight                 = undef,
  $enable_mailnotify                      = undef,
  $enable_recentchangesbox                = undef,
  $enable_page_public                     = undef,
  $readonly                               = undef,
  $wiki_name                              = undef,
  $admin_user                             = undef,
  $admin_passwd                           = undef,
  $encrypted_passwd                       = undef,
  $enable_reverse_dns                     = undef,
  $zipdump_auth                           = undef,
  $enable_raw_html                        = undef,
  $enable_raw_html_lockedonly             = undef,
  $enable_raw_html_safe                   = undef,
  $disabled_actions                       = undef,
  $insecure_actions_localhost_only        = undef,
  $enable_moderatedpage_all               = undef,
  $access_log                             = undef,
  $access_log_sql                         = undef,
  $compress_output                        = undef,
  $cache_control                          = undef,
  $cache_control_max_age                  = undef,
  $wikidb_nocache_markup                  = undef,
  $cookie_expiration_days                 = undef,
  $cookie_domain                          = undef,
  $session_save_path                      = undef,
  $use_db_session                         = undef,
  $database_type                          = undef,
  $database_prefix                        = undef,
  $database_dsn                           = undef,
  $database_persistent                    = undef,
  $database_session_table                 = undef,
  $database_directory                     = undef,
  $database_dba_handler                   = undef,
  $database_timeout                       = undef,
  $database_optimise_frequency            = undef,
  $dbadmin_user                           = undef,
  $dbadmin_passwd                         = undef,
  $usecache                               = undef,
  $major_min_keep                         = undef,
  $minor_min_keep                         = undef,
  $major_max_age                          = undef,
  $major_keep                             = undef,
  $minor_max_age                          = undef,
  $minor_keep                             = undef,
  $author_max_age                         = undef,
  $author_keep                            = undef,
  $author_min_age                         = undef,
  $author_max_keep                        = undef,
  $allow_anon_user                        = undef,
  $allow_anon_edit                        = undef,
  $allow_bogo_login                       = undef,
  $allow_user_passwords                   = undef,
  $user_auth_order                        = undef,
  $enable_auth_openid                     = undef,
  $password_length_minimum                = undef,
  $user_auth_policy                       = undef,
  $enable_pageperm                        = undef,
  $ldap_auth_host                         = undef,
  $ldap_base_dn                           = undef,
  $ldap_set_option                        = undef,
  $ldap_auth_user                         = undef,
  $ldap_auth_password                     = undef,
  $ldap_search_field                      = undef,
  $ldap_search_filter                     = undef,
  $ldap_ou_users                          = undef,
  $ldap_ou_group                          = undef,
  $imap_auth_host                         = undef,
  $pop3_auth_host                         = undef,
  $pop3_auth_port                         = undef,
  $auth_user_file                         = undef,
  $auth_user_file_storable                = undef,
  $auth_sess_user                         = undef,
  $auth_sess_level                        = undef,
  $group_method                           = undef,
  $category_group_page                    = undef,
  $auth_group_file                        = undef,
  $dbauth_auth_dsn                        = undef,
  $dbauth_auth_user_exists                = undef,
  $dbauth_auth_crypt_method               = undef,
  $dbauth_auth_check                      = undef,
  $dbauth_auth_update                     = undef,
  $dbauth_auth_create                     = undef,
  $dbauth_pref_select                     = undef,
  $dbauth_pref_update                     = undef,
  $dbauth_pref_insert                     = undef,
  $theme                                  = undef,
  $default_language                       = undef,
  $wiki_pgsrc                             = undef,
  $default_wiki_pgsrc                     = undef,
  $default_wiki_pages                     = undef,
  $allowed_protocols                      = undef,
  $inline_images                          = undef,
  $wiki_name_regexp                       = undef,
  $interwiki_map_file                     = undef,
  $warn_nonpublic_interwikimap            = undef,
  $keywords                               = undef,
  $copyrightpage_title                    = undef,
  $copyrightpage_url                      = undef,
  $authorpage_title                       = undef,
  $authorpage_url                         = undef,
  $toc_full_syntax                        = undef,
  $enable_markup_color                    = undef,
  $disable_markup_wikiword                = undef,
  $enable_markup_divspan                  = undef,
  $server_name                            = undef,
  $server_port                            = undef,
  $server_protocol                        = undef,
  $script_name                            = undef,
  $data_path                              = undef,
  $phpwiki_dir                            = undef,
  $use_path_info                          = undef,
  $virtual_path                           = undef,
  $upload_file_path                       = undef,
  $upload_data_path                       = undef,
  $temp_dir                               = undef,
  $allowed_load                           = undef,
  $strict_mailable_pagedumps              = undef,
  $default_dump_dir                       = undef,
  $html_dump_dir                          = undef,
  $html_dump_suffix                       = undef,
  $max_upload_size                        = undef,
  $minor_edit_timeout                     = undef,
  $recent_changes                         = undef,
  $disable_http_redirect                  = undef,
  $disable_getimagesize                   = undef,
  $editing_policy                         = undef,
  $fortune_dir                            = undef,
  $toolbar_pagelink_pulldown              = undef,
  $toolbar_template_pulldown              = undef,
  $toolbar_image_pulldown                 = undef,
  $fulltextsearch_stoplist                = undef,
  $google_license_key                     = undef,
  $use_external_html2pdf                  = undef,
  $external_html2pdf_pagelist             = undef,
  $babycart_path                          = undef,
  $rateit_imgprefix                       = undef,
  $graphviz_exe                           = undef,
  $ttfont                                 = undef,
  $visualwikifont                         = undef,
  $visualwiki_allowoptions                = undef,
  $ploticus_exe                           = undef,
  $ploticus_prefabs                       = undef,
  $my_jabber_id                           = undef,
  $phpweather_base_dir                    = undef,
  $plugin_cached_database                 = undef,
  $plugin_cached_cache_dir                = undef,
  $plugin_cached_filename_prefix          = undef,
  $plugin_cached_highwater                = undef,
  $plugin_cached_maxlifetime              = undef,
  $plugin_cached_maxarglen                = undef,
  $plugin_cached_usecache                 = undef,
  $plugin_cached_force_syncmap            = undef,
  $plugin_cached_imgtypes                 = undef,
  # END config.ini

) {

  if versioncmp( $version, '1.5.5') == 1 {
    fail('PhpWiki versions greater than 1.5.5 are not supported.')
  }

  contain '::phpwiki::install'
  contain '::phpwiki::config'
  contain '::phpwiki::patch'

  Class['::phpwiki::install'] ->
  Class['::phpwiki::patch'] ->
  Class['::phpwiki::config']

}